'use client'

import { useState, useCallback, useMemo } from 'react'
import { Loader2, Download, Palette } from 'lucide-react'
import { useClientDashboard, fmtNum, SOURCE_LABELS, SENTIMENT_COLORS } from '@/hooks/use-client-dashboard'
import { format } from 'date-fns'

const DATE_RANGES = [
  { label: 'Last 7 days', value: 7 },
  { label: 'Last 30 days', value: 30 },
  { label: 'Last 90 days', value: 90 },
]

const COLOR_PRESETS = [
  { label: 'Gold (Default)', value: '#D4941A' },
  { label: 'Indigo', value: '#4f46e5' },
  { label: 'Teal', value: '#0d9488' },
  { label: 'Slate', value: '#334851' },
  { label: 'Rose', value: '#e11d48' },
  { label: 'Emerald', value: '#059669' },
  { label: 'Purple', value: '#7c3aed' },
  { label: 'Blue', value: '#2563eb' },
]

const hexToRgb = (hex: string): { r: number; g: number; b: number } => {
  const h = hex.replace('#', '')
  return { r: parseInt(h.substring(0, 2), 16), g: parseInt(h.substring(2, 4), 16), b: parseInt(h.substring(4, 6), 16) }
}

const CC: [number, number, number][] = [
  [249,115,22],[59,130,246],[16,185,129],[139,92,246],[6,182,212],[236,72,153],[234,179,8],[99,102,241],[244,63,94],
]

export default function PdfReportPage() {
  const [days, setDays] = useState(30)
  const { data, isLoading } = useClientDashboard(days)
  const [exporting, setExporting] = useState(false)
  const [brandColor, setBrandColor] = useState('#D4941A')

  const BRAND = useMemo(() => hexToRgb(brandColor), [brandColor])

  const sourceEntries = useMemo(() => data ? Object.entries(data.sourceCounts).sort(([,a],[,b]) => b - a) : [], [data])

  const mediaStats = useMemo(() => {
    if (!data) return []
    const types = Array.from(new Set(data.mentions.map(m => m.type === 'social' ? 'Social Media' : m.type.charAt(0).toUpperCase() + m.type.slice(1))))
    return types.map(type => {
      const items = data.mentions.filter(m => (m.type === 'social' ? 'Social Media' : m.type.charAt(0).toUpperCase() + m.type.slice(1)) === type)
      return { type, mentions: items.length, reach: items.reduce((s,m) => s + m.reach, 0), positive: items.filter(m => m.sentiment === 'positive').length, negative: items.filter(m => m.sentiment === 'negative').length, neutral: items.filter(m => m.sentiment === 'neutral').length }
    }).sort((a,b) => b.mentions - a.mentions)
  }, [data])

  const topSources = useMemo(() => {
    if (!data) return []
    const map: Record<string, { name: string; count: number; reach: number }> = {}
    data.mentions.forEach(m => { if (!map[m.source]) map[m.source] = { name: m.source, count: 0, reach: 0 }; map[m.source].count++; map[m.source].reach += m.reach })
    return Object.values(map).sort((a,b) => b.count - a.count).slice(0, 10)
  }, [data])

  const handleExport = useCallback(async () => {
    if (!data) return
    setExporting(true)
    try {
      const jsPDF = (await import('jspdf')).default
      const autoTable = (await import('jspdf-autotable')).default
      const doc = new jsPDF({ orientation: 'landscape', unit: 'in', format: [13.33, 7.5] })
      const W = 13.33, H = 7.5, s = data.summary
      const clientName = data.client.name
      const rangeStart = format(new Date(Date.now() - days * 86400000), 'MMMM d, yyyy')
      const rangeEnd = format(new Date(), 'MMMM d, yyyy')
      const tri = (x1:number,y1:number,x2:number,y2:number,x3:number,y3:number) => { doc.lines([[x2-x1,y2-y1],[x3-x2,y3-y2],[x1-x3,y1-y3]],x1,y1,[1,1],'F',true) }
      const accent = () => { doc.setFillColor(BRAND.r,BRAND.g,BRAND.b); doc.rect(0,0,W,0.06,'F') }
      const pageTitle = (t:string, y=0.8) => { doc.setFontSize(22); doc.setTextColor(31,41,55); doc.setFont('helvetica','bold'); doc.text(t,0.6,y) }

      // PAGE 1: Cover
      doc.setFillColor(BRAND.r,BRAND.g,BRAND.b); doc.rect(0,0,W,H,'F')
      doc.setFontSize(36); doc.setTextColor(255,255,255); doc.setFont('helvetica','bold')
      doc.text('MEDIA PRESENCE',0.8,2.8); doc.text('ANALYSIS REPORT',0.8,3.4)
      doc.setFontSize(16); doc.setFont('helvetica','normal'); doc.text(clientName,0.8,4.2)
      doc.setFontSize(13); doc.text(`${rangeStart} – ${rangeEnd}`,0.8,4.7)
      doc.setFontSize(9); doc.text('Generated by Ovaview Media Monitoring',0.8,6.8)
      doc.text(format(new Date(),'MMMM d, yyyy'),0.8,7.0)

      // PAGE 2: Executive Summary
      doc.addPage([W,H],'landscape'); accent(); pageTitle('Executive Summary')
      doc.setFontSize(12); doc.setTextColor(75,85,99); doc.setFont('helvetica','normal')
      const brief = [`This report provides an analysis of the media presence for ${clientName}.`,`Data captured from ${rangeStart} to ${rangeEnd}.`,'',`During this period, ${clientName} received ${s.totalMentions} mentions`,`across all monitored media channels with a social media reach of ${fmtNum(s.totalReach)}.`]
      brief.forEach((l,i) => doc.text(l,0.6,1.4+i*0.35))
      const kpis = [{l:'Total Mentions',v:s.totalMentions.toString(),c:[31,41,55]},{l:'SM Reach',v:fmtNum(s.totalReach),c:[31,41,55]},{l:'Interactions',v:fmtNum(s.totalInteractions),c:[31,41,55]},{l:'Positive',v:s.positive.toString(),c:[16,185,129]},{l:'Negative',v:s.negative.toString(),c:[239,68,68]},{l:'Neutral',v:s.neutral.toString(),c:[107,114,128]}]
      kpis.forEach((k,i) => {
        const kx=0.6+i*2.0, ky=3.8
        doc.setFillColor(249,250,251); doc.roundedRect(kx,ky,1.8,1.0,0.06,0.06,'F')
        doc.setDrawColor(229,231,235); doc.setLineWidth(0.01); doc.roundedRect(kx,ky,1.8,1.0,0.06,0.06,'S')
        doc.setFontSize(8); doc.setTextColor(107,114,128); doc.setFont('helvetica','normal'); doc.text(k.l.toUpperCase(),kx+0.15,ky+0.3)
        doc.setFontSize(22); doc.setTextColor(k.c[0],k.c[1],k.c[2]); doc.setFont('helvetica','bold'); doc.text(k.v,kx+0.15,ky+0.7)
      })

      // PAGE 3: Media Sources Pie
      doc.addPage([W,H],'landscape'); accent(); pageTitle('Media Sources Distribution')
      const pieData = sourceEntries.map(([k,c]) => ({ name: SOURCE_LABELS[k]||k, value: c }))
      const pieTotal = pieData.reduce((s,d) => s+d.value, 0)
      if (pieTotal > 0) {
        const pcx=3.5, pcy=4.0, pr=2.2; let sa=-Math.PI/2
        pieData.forEach((d,i) => {
          const sl=(d.value/pieTotal)*2*Math.PI, c=CC[i%CC.length]; doc.setFillColor(c[0],c[1],c[2])
          const steps=Math.max(20,Math.ceil(sl/0.05))
          for(let st=0;st<steps;st++){const a1=sa+(sl*st)/steps,a2=sa+(sl*(st+1))/steps;tri(pcx,pcy,pcx+pr*Math.cos(a1),pcy+pr*Math.sin(a1),pcx+pr*Math.cos(a2),pcy+pr*Math.sin(a2))}
          doc.setDrawColor(255,255,255);doc.setLineWidth(0.02);doc.line(pcx,pcy,pcx+pr*Math.cos(sa),pcy+pr*Math.sin(sa))
          sa+=sl
        })
        let ly=1.6; doc.setFontSize(11)
        pieData.forEach((d,i) => {
          const c=CC[i%CC.length]; doc.setFillColor(c[0],c[1],c[2]); doc.rect(7.5,ly-0.08,0.2,0.2,'F')
          doc.setTextColor(55,65,81); doc.setFont('helvetica','normal')
          doc.text(`${d.name}  (${d.value} — ${((d.value/pieTotal)*100).toFixed(1)}%)`,7.9,ly+0.05); ly+=0.4
        })
      }

      // PAGE 4: Scope of Coverage cards
      doc.addPage([W,H],'landscape'); accent(); pageTitle('Scope of Coverage')
      doc.setFontSize(11); doc.setTextColor(107,114,128); doc.setFont('helvetica','normal')
      doc.text(`Breakdown of ${s.totalMentions} mentions across all media types`,0.6,1.2)
      const cW=3.6, cH=2.2, cCols=3, cGx=0.4, cGy=0.4
      mediaStats.forEach((ms,i) => {
        const col=i%cCols, row=Math.floor(i/cCols), cx2=0.6+col*(cW+cGx), cy2=1.8+row*(cH+cGy)
        doc.setFillColor(249,250,251); doc.roundedRect(cx2,cy2,cW,cH,0.08,0.08,'F')
        doc.setDrawColor(229,231,235); doc.setLineWidth(0.01); doc.roundedRect(cx2,cy2,cW,cH,0.08,0.08,'S')
        doc.setFontSize(12); doc.setTextColor(BRAND.r,BRAND.g,BRAND.b); doc.setFont('helvetica','bold'); doc.text(ms.type,cx2+0.2,cy2+0.4)
        doc.setFontSize(28); doc.setTextColor(31,41,55); doc.text(ms.mentions.toString(),cx2+0.2,cy2+1.0)
        doc.setFontSize(9); doc.setTextColor(107,114,128); doc.setFont('helvetica','normal'); doc.text('mentions',cx2+0.2,cy2+1.3)
        doc.setFontSize(10); doc.setTextColor(75,85,99); doc.text(`Reach: ${fmtNum(ms.reach)}`,cx2+0.2,cy2+1.7)
        const bx=cx2+0.2, by=cy2+1.85, bw=cW-0.4, tot=ms.positive+ms.negative+ms.neutral||1
        const pw=(ms.positive/tot)*bw, nw=(ms.neutral/tot)*bw, ngw=(ms.negative/tot)*bw
        if(pw>0){doc.setFillColor(16,185,129);doc.roundedRect(bx,by,pw,0.12,0.03,0.03,'F')}
        if(nw>0){doc.setFillColor(107,114,128);doc.rect(bx+pw,by,nw,0.12,'F')}
        if(ngw>0){doc.setFillColor(239,68,68);doc.roundedRect(bx+pw+nw,by,ngw,0.12,0.03,0.03,'F')}
      })

      // PAGE 5: Top Sources bar chart
      doc.addPage([W,H],'landscape'); accent(); pageTitle('Top Media Sources')
      if (topSources.length > 0) {
        const maxVal = Math.max(...topSources.map(s => s.count), 1)
        const chartX=1.5, chartY=1.4, chartW2=10.0, chartH2=5.0
        doc.setDrawColor(229,231,235); doc.setLineWidth(0.01)
        doc.line(chartX,chartY,chartX,chartY+chartH2); doc.line(chartX,chartY+chartH2,chartX+chartW2,chartY+chartH2)
        const yTicks=5
        for(let t=0;t<=yTicks;t++){
          const val=Math.round((maxVal*t)/yTicks), ty=chartY+chartH2-(chartH2*t)/yTicks
          doc.setFontSize(8); doc.setTextColor(156,163,175); doc.text(val.toString(),chartX-0.1,ty+0.03,{align:'right'})
          if(t>0){doc.setDrawColor(243,244,246);doc.line(chartX,ty,chartX+chartW2,ty)}
        }
        const barGap=0.15, barW3=Math.min((chartW2-barGap*(topSources.length+1))/topSources.length,0.7)
        const totalBW=topSources.length*barW3+(topSources.length-1)*barGap
        const offX=(chartW2-totalBW)/2
        topSources.forEach((src,i) => {
          const c=CC[i%CC.length], barH=(src.count/maxVal)*chartH2
          const bx=chartX+offX+i*(barW3+barGap), by=chartY+chartH2-barH
          doc.setFillColor(c[0],c[1],c[2]); doc.roundedRect(bx,by,barW3,barH,0.03,0.03,'F')
          doc.setFontSize(6); doc.setTextColor(75,85,99)
          const lbl=src.name.length>14?src.name.slice(0,13)+'…':src.name
          doc.text(lbl,bx+barW3/2,chartY+chartH2+0.2,{align:'center'})
          doc.setFontSize(7); doc.setTextColor(31,41,55); doc.setFont('helvetica','bold')
          doc.text(src.count.toString(),bx+barW3/2,by-0.1,{align:'center'})
          doc.setFont('helvetica','normal')
        })
      }

      // PAGE 6: Sentiment Analysis pie
      doc.addPage([W,H],'landscape'); accent(); pageTitle('Sentiment Analysis')
      const sentData = [{name:'Positive',value:s.positive,c:[16,185,129]},{name:'Neutral',value:s.neutral,c:[107,114,128]},{name:'Negative',value:s.negative,c:[239,68,68]}]
      const sentTotal = s.positive+s.neutral+s.negative
      if (sentTotal > 0) {
        const scx=3.5, scy=4.0, sr=2.2; let ssa=-Math.PI/2
        sentData.forEach(d => {
          const sl=(d.value/sentTotal)*2*Math.PI; doc.setFillColor(d.c[0],d.c[1],d.c[2])
          const steps=Math.max(20,Math.ceil(sl/0.05))
          for(let st=0;st<steps;st++){const a1=ssa+(sl*st)/steps,a2=ssa+(sl*(st+1))/steps;tri(scx,scy,scx+sr*Math.cos(a1),scy+sr*Math.sin(a1),scx+sr*Math.cos(a2),scy+sr*Math.sin(a2))}
          doc.setDrawColor(255,255,255);doc.setLineWidth(0.02);doc.line(scx,scy,scx+sr*Math.cos(ssa),scy+sr*Math.sin(ssa))
          ssa+=sl
        })
        let sly=2.0; doc.setFontSize(14)
        sentData.forEach(d => {
          doc.setFillColor(d.c[0],d.c[1],d.c[2]); doc.rect(7.5,sly-0.1,0.25,0.25,'F')
          doc.setTextColor(55,65,81); doc.setFont('helvetica','normal')
          const pct=((d.value/sentTotal)*100).toFixed(1)
          doc.text(`${d.name}: ${d.value} (${pct}%)`,8.0,sly+0.08); sly+=0.5
        })
        doc.setFontSize(11); doc.setTextColor(75,85,99)
        const dominant = sentData.reduce((a,b) => a.value >= b.value ? a : b)
        doc.text(`The overall sentiment is predominantly ${dominant.name.toLowerCase()},`,7.5,4.0)
        doc.text(`accounting for ${((dominant.value/sentTotal)*100).toFixed(1)}% of all mentions.`,7.5,4.4)
      }

      // PAGE 7: Recent Mentions table
      doc.addPage([W,H],'landscape'); accent(); pageTitle('Recent Mentions')
      doc.setFontSize(10); doc.setTextColor(107,114,128); doc.setFont('helvetica','normal')
      doc.text(`Showing up to 40 most recent mentions`,0.6,1.15)

      const mentionRows = data.mentions.slice(0,40).map(m => [
        format(new Date(m.date),'MMM d, yyyy'),
        m.type === 'social' ? (m.platform || 'Social') : m.type.charAt(0).toUpperCase() + m.type.slice(1),
        m.title.length > 55 ? m.title.slice(0,55)+'...' : m.title,
        m.source.length > 22 ? m.source.slice(0,22)+'...' : m.source,
        m.sentiment.charAt(0).toUpperCase() + m.sentiment.slice(1),
        fmtNum(m.reach),
      ])
      autoTable(doc, {
        startY: 1.4,
        head: [['Date','Type','Title','Source','Sentiment','Reach']],
        body: mentionRows,
        theme: 'grid',
        headStyles: { fillColor: [BRAND.r,BRAND.g,BRAND.b], textColor: 255, fontSize: 9, font: 'helvetica', fontStyle: 'bold' },
        bodyStyles: { fontSize: 8, textColor: [75,85,99] },
        alternateRowStyles: { fillColor: [249,250,251] },
        columnStyles: { 0:{cellWidth:1.2}, 1:{cellWidth:1.0}, 2:{cellWidth:4.5}, 3:{cellWidth:2.0}, 4:{cellWidth:1.0}, 5:{cellWidth:0.8} },
        margin: { left: 0.6, right: 0.6 },
        styles: { cellPadding: 0.08 },
      })

      // PAGE 8: Back cover
      doc.addPage([W,H],'landscape')
      doc.setFillColor(BRAND.r,BRAND.g,BRAND.b); doc.rect(0,0,W,H,'F')
      doc.setFontSize(28); doc.setTextColor(255,255,255); doc.setFont('helvetica','bold')
      doc.text('Thank You',W/2,3.0,{align:'center'})
      doc.setFontSize(14); doc.setFont('helvetica','normal')
      doc.text(clientName,W/2,3.8,{align:'center'})
      doc.setFontSize(11)
      doc.text('Ovaview Media Monitoring',W/2,5.0,{align:'center'})
      doc.text(format(new Date(),'MMMM yyyy'),W/2,5.4,{align:'center'})

      // Page numbers on all pages
      const totalPages = doc.getNumberOfPages()
      for(let i=2;i<=totalPages-1;i++){
        doc.setPage(i); doc.setFontSize(7); doc.setTextColor(180,180,180)
        doc.text(`${i} / ${totalPages}`,W-0.5,H-0.3,{align:'right'})
        doc.text('Ovaview Media Monitoring',0.6,H-0.3)
      }

      doc.save(`${clientName.replace(/\s+/g,'_')}_Media_Report_${format(new Date(),'yyyy-MM-dd')}.pdf`)
    } catch(err) { console.error('PDF export failed:',err) }
    finally { setExporting(false) }
  }, [data, days, sourceEntries, mediaStats, topSources, BRAND])

  if (isLoading || !data) {
    return <div className="p-6 flex items-center justify-center min-h-[60vh]"><Loader2 className="h-8 w-8 animate-spin text-purple-500" /></div>
  }

  const s = data.summary

  return (
    <div className="p-4 sm:p-6 space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-bold text-gray-800">PDF Report</h1>
          <p className="text-sm text-gray-500">Professional multi-page media monitoring report</p>
        </div>
        <div className="flex items-center gap-3">
          <select value={days} onChange={e => setDays(Number(e.target.value))}
            className="text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-purple-500">
            {DATE_RANGES.map(r => <option key={r.value} value={r.value}>{r.label}</option>)}
          </select>
          <button onClick={handleExport} disabled={exporting}
            className="flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-medium text-white bg-indigo-500 hover:bg-indigo-600 disabled:opacity-50 transition-colors">
            {exporting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
            {exporting ? 'Generating...' : 'Download PDF'}
          </button>
        </div>
      </div>

      {/* Options bar */}
      <div className="bg-white rounded-lg border border-gray-200 p-4 flex flex-col sm:flex-row items-start sm:items-center gap-4">
        {/* Color picker */}
        <div className="flex items-center gap-2">
          <Palette className="h-4 w-4 text-gray-400" />
          <span className="text-sm text-gray-600">Report color:</span>
          <div className="flex items-center gap-1.5">
            {COLOR_PRESETS.map(preset => (
              <button
                key={preset.value}
                onClick={() => setBrandColor(preset.value)}
                title={preset.label}
                className={`w-6 h-6 rounded-full border-2 transition-all ${
                  brandColor === preset.value ? 'border-gray-800 scale-110' : 'border-transparent hover:border-gray-300'
                }`}
                style={{ backgroundColor: preset.value }}
              />
            ))}
            <div className="relative ml-1">
              <input
                type="color"
                value={brandColor}
                onChange={e => setBrandColor(e.target.value)}
                className="w-6 h-6 rounded cursor-pointer border border-gray-200"
                title="Custom color"
              />
            </div>
          </div>
        </div>
      </div>

      {/* Preview slides */}
      <div className="space-y-6">
        {/* Slide 2: Summary */}
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Page 2 — Executive Summary</p>
          <h3 className="text-lg font-bold text-gray-800 mb-4">Executive Summary</h3>
          <p className="text-sm text-gray-600 mb-6">
            During this period, {data.client.name} received {s.totalMentions} mentions across all monitored media channels with a social media reach of {fmtNum(s.totalReach)}.
          </p>
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-3">
            {[{l:'Mentions',v:s.totalMentions},{l:'SM Reach',v:s.totalReach},{l:'Interactions',v:s.totalInteractions},{l:'Positive',v:s.positive},{l:'Negative',v:s.negative},{l:'Neutral',v:s.neutral}].map(st => (
              <div key={st.l} className="text-center p-3 bg-gray-50 rounded-lg">
                <p className="text-[10px] uppercase text-gray-400">{st.l}</p>
                <p className="text-xl font-bold text-gray-800">{fmtNum(st.v)}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Slide 3: Sources Pie */}
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Page 3 — Media Sources Distribution</p>
          <h3 className="text-lg font-bold text-gray-800 mb-4">Media Sources Distribution</h3>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            {sourceEntries.map(([key, count], i) => (
              <div key={key} className="flex items-center gap-2 p-2 rounded bg-gray-50">
                <div className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: `rgb(${CC[i%CC.length].join(',')})` }} />
                <span className="text-sm text-gray-700 flex-1">{SOURCE_LABELS[key]||key}</span>
                <span className="text-sm font-semibold text-gray-800">{count}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Slide 4: Scope */}
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Page 4 — Scope of Coverage</p>
          <h3 className="text-lg font-bold text-gray-800 mb-4">Scope of Coverage</h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {mediaStats.map(ms => (
              <div key={ms.type} className="bg-gray-50 rounded-lg p-4">
                <p className="text-sm font-semibold" style={{ color: brandColor }}>{ms.type}</p>
                <p className="text-3xl font-bold text-gray-800 mt-1">{ms.mentions}</p>
                <p className="text-xs text-gray-400">mentions · Reach: {fmtNum(ms.reach)}</p>
                <div className="flex gap-0.5 mt-2 h-2 rounded overflow-hidden">
                  {ms.positive > 0 && <div className="bg-emerald-500" style={{flex:ms.positive}} />}
                  {ms.neutral > 0 && <div className="bg-gray-400" style={{flex:ms.neutral}} />}
                  {ms.negative > 0 && <div className="bg-red-500" style={{flex:ms.negative}} />}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Slide 5: Top Sources */}
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Page 5 — Top Media Sources</p>
          <h3 className="text-lg font-bold text-gray-800 mb-4">Top Media Sources</h3>
          <div className="space-y-2">
            {topSources.map((src, i) => {
              const maxCount = topSources[0]?.count || 1
              return (
                <div key={i} className="flex items-center gap-3">
                  <span className="text-sm text-gray-600 w-40 truncate">{src.name}</span>
                  <div className="flex-1 bg-gray-100 rounded-full h-5 overflow-hidden">
                    <div className="h-full rounded-full" style={{ width: `${(src.count/maxCount)*100}%`, backgroundColor: `rgb(${CC[i%CC.length].join(',')})` }} />
                  </div>
                  <span className="text-sm font-semibold text-gray-800 w-10 text-right">{src.count}</span>
                </div>
              )
            })}
          </div>
        </div>

        {/* Slide 6: Sentiment */}
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Page 6 — Sentiment Analysis</p>
          <h3 className="text-lg font-bold text-gray-800 mb-4">Sentiment Analysis</h3>
          <div className="flex gap-4">
            {[{l:'Positive',v:s.positive,c:'bg-emerald-500'},{l:'Neutral',v:s.neutral,c:'bg-gray-400'},{l:'Negative',v:s.negative,c:'bg-red-500'}].map(st => (
              <div key={st.l} className="flex items-center gap-2">
                <div className={`w-4 h-4 rounded ${st.c}`} />
                <span className="text-sm text-gray-700">{st.l}: {st.v} ({((st.v/(s.totalMentions||1))*100).toFixed(1)}%)</span>
              </div>
            ))}
          </div>
        </div>

        {/* Slide 7: Mentions table */}
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Page 7 — Recent Mentions</p>
          <h3 className="text-lg font-bold text-gray-800 mb-4">Recent Mentions (Top 20)</h3>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead><tr className="bg-gray-50 text-left">
                <th className="px-3 py-2 font-medium text-gray-500">Date</th>
                <th className="px-3 py-2 font-medium text-gray-500">Type</th>
                <th className="px-3 py-2 font-medium text-gray-500">Title</th>
                <th className="px-3 py-2 font-medium text-gray-500">Sentiment</th>
                <th className="px-3 py-2 font-medium text-gray-500 text-right">Reach</th>
              </tr></thead>
              <tbody className="divide-y divide-gray-100">
                {data.mentions.slice(0,20).map((m,i) => {
                  const sc = SENTIMENT_COLORS[m.sentiment as keyof typeof SENTIMENT_COLORS] || SENTIMENT_COLORS.neutral
                  return (<tr key={i} className="hover:bg-gray-50">
                    <td className="px-3 py-2 text-gray-600 whitespace-nowrap">{format(new Date(m.date),'MMM d')}</td>
                    <td className="px-3 py-2 text-gray-600 capitalize">{m.type==='social'?(m.platform||'Social'):m.type}</td>
                    <td className="px-3 py-2 text-gray-800 truncate max-w-[300px]">{m.title}</td>
                    <td className="px-3 py-2"><span className={`px-2 py-0.5 rounded text-xs ${sc.bg} ${sc.text}`}>{m.sentiment.charAt(0).toUpperCase()+m.sentiment.slice(1)}</span></td>
                    <td className="px-3 py-2 text-right text-gray-600">{fmtNum(m.reach)}</td>
                  </tr>)
                })}
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  )
}
